### ISSUE TITLE
Steps to install this plugin

### ISSUE THREAD

**Issue by jdnichollsc** [nolanlawson/sqlite-plugin-fork#1]
Hi men, I want to use PouchDB with SQLite... But what are the steps to install this? Do you need to modify config.xml?

Thanks in advance, Nicholls

**Comment by nolanlawson** [comment]
The steps are on the README, but actually I should deprecate this repo. Nowadays you can use the `androidDatabaseImplementation` option to use the older implementation of the SQLite Plugin: http://pouchdb.com/api.html#create_database (set it to 2)

Also TBH you probably should not use the SQLite Plugin on Android if you can avoid it. It is slower, buggier, and offers no benefit. (Android IndexedDB/WebSQL already has no storage limit, unless you need to store >200MB.) The SQLite Plugin is really only useful on iOS these days.

**Comment by jdnichollsc** [comment]
Thanks for all :D

**Comment by jdnichollsc** [comment]
Hi man, this is my example: https://gist.github.com/jdnichollsc/f82592d6f303aaebfb9f

My demoDB.db file has recors in a table, but the alert show "0" records. ¿What do you thing?
